#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          sns
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Short-Description: Create sns directories
### END INIT INFO

export SNS_RUNROOT=/var/run/sns
export SNS_TMPROOT=/var/tmp/sns

run() {
    ARGS=""
    SNS_IDENT=""
    while test x"$1" != x--; do
        case "$1" in
            -d|-r|-rd|-dr)
                ARGS="$1 $ARGS"
                ;;
            -*)
                echo Invalid option: "$1"
                exit 1
                ;;
            *)
                if test -n "$SNS_IDENT"; then
                    echo Invalid option: "$1"
                    exit 1
                else
                    SNS_IDENT="$1"
                fi
                ;;
        esac
        shift
    done

    shift

    if test -z "$SNS_IDENT"; then
        echo Need to provide identifier
        exit 1
    fi

    if test -z "$1"; then
        echo No program specified
        exit 1
    fi

    export SNS_IDENT
    export SNS_RUNDIR=$SNS_RUNROOT/$SNS_IDENT
    export SNS_TMPDIR=$SNS_TMPROOT/$SNS_IDENT

    if test ! -d $SNS_RUNDIR; then  mkdir $SNS_RUNDIR; fi
    if test ! -d $SNS_TMPDIR; then  mkdir $SNS_TMPDIR; fi

    exec achcop $ARGS              \
        -P $SNS_RUNDIR/ppid        \
        -p $SNS_RUNDIR/pid         \
        -o $SNS_TMPDIR/out         \
        -e $SNS_TMPDIR/out         \
        -- $@
}


start() {
    if test ! -d $SNS_RUNROOT; then
        mkdir -m 1777 $SNS_RUNROOT
    fi
    if test ! -d $SNS_TMPROOT; then
        mkdir -m 1777 $SNS_TMPROOT
    fi

    ach mk -o 666 sns-log

    run -dr snslogd -- snslogd
}


cmd_kill() {
    ARGS=""
    SNS_IDENT="."
    while test -n "$1"; do
        case "$1" in
            -*) ARGS="$1 $ARGS"
                ;;
            *) SNS_IDENT="$1"
                ;;
        esac
        shift
    done
    PID=`cat "$SNS_RUNROOT/$SNS_IDENT/ppid"`
    if kill $ARGS $PID; then
        echo signaled "\`$SNS_IDENT'"
    fi
}



stop() {
    for ident in `ls $SNS_RUNROOT`; do
        if test -f $SNS_RUNROOT/$ident/ppid; then
            cmd_kill $ident || echo "Couldn't kill $ident"
        fi
    done
    ach rm sns-log
}

cmd_ls() {
    for ident in `ls $SNS_RUNROOT`; do
        if test -d $SNS_RUNROOT/$ident; then
            # check parent
            SNS_PPID=`sns-trylock $SNS_RUNROOT/$ident/ppid || echo DEAD`
            echo $ident parent $SNS_PPID

            # check child
            SNS_PID=`sns-trylock $SNS_RUNROOT/$ident/pid || echo DEAD`
            echo $ident self $SNS_PID

        fi
    done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    run)
        shift
        run $@
        ;;
    ls)
        cmd_ls
        ;;
    kill)
        shift
        cmd_kill $@
        ;;
    restart)
        stop
        start
        ;;
    force-reload)
        stop
        start
        ;;
    *)
        exit 1;
esac
