#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          sns
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Short-Description: Create sns directories
### END INIT INFO

export SNS_RUNROOT=/var/run/sns

start() {
    if test ! -d $SNS_RUNROOT; then
        mkdir -m 1777 $SNS_RUNROOT
    fi
}

run() {
    if test ! -d $SNS_RUNDIR; then  mkdir $SNS_RUNDIR; fi
    ARGS=""
    SNS_IDENT=""
    while test x"$1" != x--; do
        case "$1" in
            -d|-r|-rd|-dr)
                ARGS="$1 $ARGS"
                ;;
            -*)
                echo Invalid option: "$1"
                exit 1
                ;;
            *)
                if test -n "$SNS_IDENT"; then
                    echo Invalid option: "$1"
                    exit 1
                else
                    SNS_IDENT="$1"
                fi
                ;;
        esac
        shift
    done

    shift

    if test -z "$SNS_IDENT"; then
        echo Need to provide identifier
        exit 1
    fi

    if test -z "$1"; then
        echo No program specified
        exit 1
    fi

    export SNS_IDENT
    export SNS_RUNDIR=$SNS_RUNROOT/$SNS_IDENT
    exec achcop $ARGS              \
        -P $SNS_RUNDIR/ppid        \
        -p $SNS_RUNDIR/pid         \
        -o $SNS_RUNDIR/out         \
        -e $SNS_RUNDIR/out         \
        -- $@
}

cmd_kill() {
    ARGS=""
    SNS_IDENT="."
    while test -n "$1"; do
        case "$1" in
            -*) ARGS="$1 $ARGS"
                ;;
            *) SNS_IDENT="$1"
                ;;
        esac
        shift
    done
    PID=`cat "$SNS_RUNROOT/$SNS_IDENT/ppid"`
    kill $ARGS $PID
}



stop() {
    for ident in `ls $SNS_RUNROOT`; do
        if test -f $SNS_RUNROOT/$ident/ppid; then
            cmd_kill $ident || echo "Couldn't kill $ident"
        fi
    done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    run)
        shift
        run $@
        ;;
    kill)
        shift
        cmd_kill $@
        ;;
    restart)
        stop
        start
        ;;
    force-reload)
        stop
        start
        ;;
    *)
        exit 1;
esac
