#!/bin/sh


sns-teleopd -j joystick \
            -y state \
            -u ref \
            -s ~/git/amino/demo/urdf/baxter/.libs/libamino_baxter.so \
            -n baxter \
            -Q 4 -m "left_s0,left_s1,left_e0,left_e1" \
            -Q 6 -m "left_w0,left_w1,left_w2" \
            -Q 5 -m "right_s0,right_s1,right_e0,right_e1" \
            -Q 7 -m "right_w0,right_w1,right_w2"
